# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
 branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'  # Specify the build agent, you can use different OS images (Ubuntu, Windows, etc.)

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $sourcePath = "$(Build.ArtifactStagingDirectory)"
      $artifactName = "drop"
      $destinationPath = "$(Pipeline.Workspace)\$artifactName"
      Copy-Item -Path $sourcePath -Destination $destinationPath -Recurse
      Write-Host "Artifacts copied to $destinationPath"

