apiVersion: apps/v1
kind: Deployment
metadata:
  name: fhir-restassured-deployment
spec:
  selector:
    matchLabels:
      app: fhir-restassured
  replicas: 2
  template:
    metadata:
      labels:
        app: fhir-restassured
    spec:
      containers:
        - name: fhir-restassured
          image: reka83/fhir-googlecloudapi-bdd-cucumber-framework:latest
          command: ["sleep", "infinity"]
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 8081

---

apiVersion: v1
kind: Service
metadata:
  name: restassured-ssvc
spec:
  selector:
    app: fhir-restassured
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8081
      nodePort: 30080
  type: NodePort
  #type: LoadBalancer  # Make sure your environment supports LoadBalancer services
